export enum LegalEntitySection {
  BUSINESS_DETAILS = "BUSINESS_DETAILS",
  BUSINESS_ACTIVITY = "BUSINESS_ACTIVITY",
  BUSINESS_REPRESENTATIVE = "BUSINESS_REPRESENTATIVE",
  BUSINESS_OWNERS = "BUSINESS_OWNERS",
  DOCUMENTS = "DOCUMENTS",
  AGREEMENT = "AGREEMENT",
}
